apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  flowLogsFlushInterval: 15s
  flowLogsFileAggregationKindForAllowed: 1
  flowLogsFileAggregationKindForDenied: 0
  flowLogsCollectTcpStats: true
  flowLogsEnableHostEndpoint: true
  dnsLogsFlushInterval: 15s
  dnsLogsFileEnabled: true
  dnsLogsFileAggregationKind: 0
  logSeverityScreen: Info
  captureRotationSeconds: 3600