apiVersion: projectcalico.org/v3
kind: StagedGlobalNetworkPolicy
metadata:
  name: default.default-deny
spec:
  tier: default
  order: 10000
  selector: "projectcalico.org/namespace in {'stars','client','management-ui','hipstershop'}"
  types:
  - Ingress
  - Egress